### ISSUE TITLE
Installed realhats, but running hats.tex ends with error

### ISSUE THREAD

**Issue by empet** [mscroggs/realhats#13]
I've just installed realhats package via  Miktex and run the file [https://github.com/mscroggs/realhats/blob/master/readme_images/hats.tex](https://github.com/mscroggs/realhats/blob/master/readme_images/hats.tex).
I cannot understand why it throws the error:

! LaTeX Error: File `hats/realhats-beret' not found.

What could be missing?
Thanks!

**Comment by empet** [comment]
I found a workaround: I also installed the package in the same folder where I put the hats.tex,
and I deleted from the realhats.sty the `hats/` from the lines like this one:
`\ifthenelse{\equal{#2}{beret}}{\renewcommand\myhat{hats/realhats-beret}\setlength{\vshif}{-0.6ex} \setlength{\hshif}{0.5ex} }{}%`
and moved all files from hats subfolder in the working one. With this setup it works.

**Comment by mscroggs** [comment]
You may need to run `texhash` or similar to re-index your LaTeX packages folder
