### ISSUE TITLE
Input without curly brackets

### ISSUE THREAD

**Issue by lquenti** [mscroggs/realhats#21]
Hey! I'm currently writing another joke package, having big inspiration of your awesome work.

While reading into it, I learned that using `input{docstrip}` is strongly seen as bad practise since this would limit it to LaTeX only instead of other *tex, which may use your file as well.

Source: http://texdoc.net/texmf-dist/doc/latex/base/docstrip.pdf Page 5 (`\input`)

Just fyi, I really like your project and will genuinely use it for my fourier analysis lecture next semester :+1: 

Cheers

**Comment by lquenti** [comment]
btw, while I'm on it: I am using a lot of your Code as boilerplate. What would be your preferred way of Copyrightincludement?

My current idea is naming your project under contributions in the readme as well as in any MIT License as Co-Copyright holder if thats fine.

(It will be MIT licensed as well)

**Comment by mscroggs** [comment]
Hi Lars

Thanks for getting in touch! We are glad you are also choosing to join us in poisoning the world in this very specific way. Thanks for the heads up about docstrip - we will look into it for the next update of realhats. And your current idea of copyright inclusion is completely fine with us; we are happen to share this very silly idea with the world.

realtranspose looks amazing.

All best, Matt & Adam
