### ISSUE TITLE
how to remove distance between letters and remove italic format?

### ISSUE THREAD

**Issue by m43stro** [mscroggs/realhats#29]
First of all, thanks for the great package gentleman!

Now the issue: I tried it in one word:

\hat[crown]{B}OX

The results looks like this:

<img width="124" alt="crown realhats latex usage" src="https://user-images.githubusercontent.com/29970891/217367841-6df6b89c-e818-4e3c-9664-81d718ae6ed6.png">

- is it possible to remove italic format?
- is it possible to remove the distance between the letters?

using it with:
\documentclass[11pt]{article}

Packages:
- geometry
- pdfpages
- babel
- pgffor, ifthen
- hyperref
- cuisine

**Comment by mscroggs** [comment]
The italic can be removed by doing `\hat[crown]{\text{B}}` (the hats assume math mode)

You could hackily remove the spacing by using negative hspace. I'll look into whether we can do this in a non hacky way

**Comment by m43stro** [comment]
thank you @mscroggs 

\kern-1em \hat[crown]{\text{B}} \kern-0.8em

fixed in a hacky way my issue
